name: flutter_app_feedback
description: Flutter Package to implement Feedback System in Flutter Project.
version: 0.0.1+1
homepage: https://github.com/imihirpaldhikar/flutter_app_feedback

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^2.5.4
  device_info_plus: ^3.1.0
  firebase_core: ^1.8.0
  firebase_storage: ^10.0.6
  image_picker: ^0.8.4+3
  flutter:
    sdk: flutter
  package_info_plus: ^1.3.0
  screenshot: ^1.2.3
  path_provider: ^2.0.5
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
