name: flutter_app_feedback
description: Flutter Package to implement Feedback System in Flutter Project.
version: 0.0.1
homepage: https://github.com/imihirpaldhikar/flutter_app_feedback

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^2.5.4
  firebase_core: ^1.8.0
  firebase_storage: ^10.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

